---

- name: Provision a {{ application_name }} server
  hosts: all
  #sudo: yes
  #sudo_user: root
  remote_user: emarty
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
    - current_password: abc123$
    - new_password: "{{ current_password }}"
  vars_files:
    - env_vars/base
    - env_vars/dev

  roles:
    - base
    - db
    - web
    - memcached
