---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}
  tags: pip

#TODO: Create symlink command

#- name: Symlink settings file
#  shell: cd {{ settings_path }}
#         && ln -s settings.py __init__.py
#  tags: link

- name: Run the Fabric db_load command
  shell: . {{ virtualenv_path }}/bin/activate
         && . {{ virtualenv_path }}/bin/postactivate
         && cd {{ application_path }}
         && fabfile.py fab db_load
  when: run_fab_db_load
  tags: fabric

- name: Run Django collectstatic
  shell: . {{ virtualenv_path }}/bin/activate
         && . {{ virtualenv_path }}/bin/postactivate
         && cd {{ application_path }}
         && python manage.py collectstatic --noinput --settings={{ django_settings_file }}
  when: run_django_collectstatic
  tags: django

#- name: Run the Django syncdb command
#  shell: . {{ virtualenv_path }}/bin/activate
#         && . {{ virtualenv_path }}/bin/postactivate
#         && cd {{ application_path }}
#         && python manage.py syncdb --noinput --settings={{ django_settings_file }}
#  when: run_django_syncdb
#  tags: django
#
#- name: Run Django South migrations
#  shell: . {{ virtualenv_path }}/bin/activate
#         && . {{ virtualenv_path }}/bin/postactivate
#         && cd {{ application_path }}
#         && python manage.py migrate --noinput --settings={{ django_settings_file }}
#  when: run_django_south_migration
#  tags: django
