---

# Application settings.
virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_path: "{{ project_path }}/{{ application_name }}"
application_log_dir: "/var/log/gunicorn/"
application_log_file: "/var/log/gunicorn/gunicorn_supervisor.log"
application_err_file: "/var/log/gunicorn/gunicorn_supervisor_err.log"
requirements_file: "{{ project_path }}/requirements.txt"
settings_root: "{{ application_path }}/settings/"
settings_path: "{{ application_path }}/settings/example/"


# Gunicorn settings
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps


# Nginx settings
nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ virtualenv_path }}/static/"
nginx_media_dir: "{{ virtualenv_path }}/media/"
